### ISSUE TITLE
Android binding progress

### ISSUE THREAD

**Issue by charlesroddie** [charlesroddie/MyScriptXamarinBinding#2]

**Comment by kumaranvellaisamy** [comment]
I tried to create binding for myscript core component. Got the below error
https://forums.xamarin.com/discussion/103921/binding-library-for-aar-file#latest

**Comment by charlesroddie** [comment]
Hi @kumaranvellaisamy sorry I did not do any work on this, because platform-bindings would have been too much work. Moreover MyScript introduced the Interactive Ink SDK which is much more promising for Xamarin use. Now there is https://developer.myscript.com/docs/interactive-ink/1.1/overview/about/ which claims to have a .NET API. This is what we have been waiting for so we will work on using this from Xamarin.Forms.
